### ISSUE TITLE
Array.prototype.map() expects a return value from arrow function

### ISSUE THREAD

**Issue by pmartiamarista** [devhammed/use-global-hook#6]
hooks.map((hook) => {
    if (typeof hook !== "function") {
      throw new TypeError(
        `Provided global hook value "${hook}" is not a function.`
      );
    }

hooks.map((hook) => {
      stores[hook] = useGlobalHook(hook);
    });
Hi, .map needs a return value. you can use forEach() to iterate de Array.  Very useful Hook by the way. I change the example with useReducer 
  const [state, dispatch] = useReducer(countReducer, {
    ...initialState,
  });
Works great!

**Comment by devhammed** [comment]
@pmartiamarista Oh yeah, I will do that ASAP and thank you for checking out the library.
